### ISSUE TITLE
wss Protocol not supported

### ISSUE THREAD

**Issue by Zhanweelee** [Iperity/node-strophe#3]
var c = new Strophe.Connection("wss://example.com/websocket/");
c.connect(jid, pass);

This error comes out and I cannot find a way to fix it.

```
Error: Protocol not supported.
    at send (/Users/jonathan/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:299:15)
    at sendFunc (/Users/jonathan/node_modules/node-strophe/strophe.js:2218:25)
    at Object._processRequest (/Users/jonathan/node_modules/node-strophe/strophe.js:2229:17)
    at Object._throttledRequestHandler (/Users/jonathan/node_modules/node-strophe/strophe.js:2266:18)
    at Object.connect (/Users/jonathan/node_modules/node-strophe/strophe.js:1648:14)
    at repl:1:12
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
```

**Comment by matthiasvdh** [comment]
Thanks for your interest, Zhanweelee.

Most likely the version we ported does not include support for WebSockets yet.

We do not plan to use that functionality ourselves.
